//go:build go1.22

// Package ApiGateway provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package ApiGateway

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for FileItemStatus.
const (
	FileItemStatusFailed     FileItemStatus = "failed"
	FileItemStatusProcessed  FileItemStatus = "processed"
	FileItemStatusProcessing FileItemStatus = "processing"
	FileItemStatusUploaded   FileItemStatus = "uploaded"
)

// Defines values for FileStatusResponseStatus.
const (
	FileStatusResponseStatusFailed     FileStatusResponseStatus = "failed"
	FileStatusResponseStatusProcessed  FileStatusResponseStatus = "processed"
	FileStatusResponseStatusProcessing FileStatusResponseStatus = "processing"
	FileStatusResponseStatusUploaded   FileStatusResponseStatus = "uploaded"
)

// Defines values for FileUploadResponseStatus.
const (
	FileUploadResponseStatusFailed     FileUploadResponseStatus = "failed"
	FileUploadResponseStatusProcessed  FileUploadResponseStatus = "processed"
	FileUploadResponseStatusProcessing FileUploadResponseStatus = "processing"
	FileUploadResponseStatusUploaded   FileUploadResponseStatus = "uploaded"
)

// Defines values for GenerateReportRequestFormat.
const (
	Excel GenerateReportRequestFormat = "excel"
	Json  GenerateReportRequestFormat = "json"
	Pdf   GenerateReportRequestFormat = "pdf"
)

// Defines values for GenerateReportRequestReportType.
const (
	GenerateReportRequestReportTypeComprehensive GenerateReportRequestReportType = "comprehensive"
	GenerateReportRequestReportTypeEnergy        GenerateReportRequestReportType = "energy"
	GenerateReportRequestReportTypeEnvironmental GenerateReportRequestReportType = "environmental"
	GenerateReportRequestReportTypeFinancial     GenerateReportRequestReportType = "financial"
	GenerateReportRequestReportTypeProduction    GenerateReportRequestReportType = "production"
)

// Defines values for GenerateReportResponseStatus.
const (
	GenerateReportResponseStatusCompleted  GenerateReportResponseStatus = "completed"
	GenerateReportResponseStatusFailed     GenerateReportResponseStatus = "failed"
	GenerateReportResponseStatusProcessing GenerateReportResponseStatus = "processing"
	GenerateReportResponseStatusQueued     GenerateReportResponseStatus = "queued"
)

// Defines values for HealthCheckResponseComponentsApiGateway.
const (
	HealthCheckResponseComponentsApiGatewayDegraded  HealthCheckResponseComponentsApiGateway = "degraded"
	HealthCheckResponseComponentsApiGatewayHealthy   HealthCheckResponseComponentsApiGateway = "healthy"
	HealthCheckResponseComponentsApiGatewayUnhealthy HealthCheckResponseComponentsApiGateway = "unhealthy"
)

// Defines values for HealthCheckResponseComponentsAuthService.
const (
	HealthCheckResponseComponentsAuthServiceDegraded  HealthCheckResponseComponentsAuthService = "degraded"
	HealthCheckResponseComponentsAuthServiceHealthy   HealthCheckResponseComponentsAuthService = "healthy"
	HealthCheckResponseComponentsAuthServiceUnhealthy HealthCheckResponseComponentsAuthService = "unhealthy"
)

// Defines values for HealthCheckResponseComponentsClickhouse.
const (
	HealthCheckResponseComponentsClickhouseDegraded  HealthCheckResponseComponentsClickhouse = "degraded"
	HealthCheckResponseComponentsClickhouseHealthy   HealthCheckResponseComponentsClickhouse = "healthy"
	HealthCheckResponseComponentsClickhouseUnhealthy HealthCheckResponseComponentsClickhouse = "unhealthy"
)

// Defines values for HealthCheckResponseComponentsKafka.
const (
	HealthCheckResponseComponentsKafkaDegraded  HealthCheckResponseComponentsKafka = "degraded"
	HealthCheckResponseComponentsKafkaHealthy   HealthCheckResponseComponentsKafka = "healthy"
	HealthCheckResponseComponentsKafkaUnhealthy HealthCheckResponseComponentsKafka = "unhealthy"
)

// Defines values for HealthCheckResponseComponentsPostgres.
const (
	HealthCheckResponseComponentsPostgresDegraded  HealthCheckResponseComponentsPostgres = "degraded"
	HealthCheckResponseComponentsPostgresHealthy   HealthCheckResponseComponentsPostgres = "healthy"
	HealthCheckResponseComponentsPostgresUnhealthy HealthCheckResponseComponentsPostgres = "unhealthy"
)

// Defines values for HealthCheckResponseComponentsRedis.
const (
	HealthCheckResponseComponentsRedisDegraded  HealthCheckResponseComponentsRedis = "degraded"
	HealthCheckResponseComponentsRedisHealthy   HealthCheckResponseComponentsRedis = "healthy"
	HealthCheckResponseComponentsRedisUnhealthy HealthCheckResponseComponentsRedis = "unhealthy"
)

// Defines values for HealthCheckResponseStatus.
const (
	Degraded  HealthCheckResponseStatus = "degraded"
	Healthy   HealthCheckResponseStatus = "healthy"
	Unhealthy HealthCheckResponseStatus = "unhealthy"
)

// Defines values for RegisterRequestRole.
const (
	RegisterRequestRoleAdmin   RegisterRequestRole = "admin"
	RegisterRequestRoleAnalyst RegisterRequestRole = "analyst"
	RegisterRequestRoleCompany RegisterRequestRole = "company"
)

// Defines values for UserInfoResponseRole.
const (
	UserInfoResponseRoleAdmin   UserInfoResponseRole = "admin"
	UserInfoResponseRoleAnalyst UserInfoResponseRole = "analyst"
	UserInfoResponseRoleCompany UserInfoResponseRole = "company"
)

// Defines values for GetApiV1AnalyticsReportsParamsReportType.
const (
	GetApiV1AnalyticsReportsParamsReportTypeComprehensive GetApiV1AnalyticsReportsParamsReportType = "comprehensive"
	GetApiV1AnalyticsReportsParamsReportTypeEnergy        GetApiV1AnalyticsReportsParamsReportType = "energy"
	GetApiV1AnalyticsReportsParamsReportTypeEnvironmental GetApiV1AnalyticsReportsParamsReportType = "environmental"
	GetApiV1AnalyticsReportsParamsReportTypeFinancial     GetApiV1AnalyticsReportsParamsReportType = "financial"
	GetApiV1AnalyticsReportsParamsReportTypeProduction    GetApiV1AnalyticsReportsParamsReportType = "production"
)

// Defines values for GetApiV1FilesParamsStatus.
const (
	Failed     GetApiV1FilesParamsStatus = "failed"
	Processed  GetApiV1FilesParamsStatus = "processed"
	Processing GetApiV1FilesParamsStatus = "processing"
	Uploaded   GetApiV1FilesParamsStatus = "uploaded"
)

// Defines values for PostApiV1FilesUploadMultipartBodyDataType.
const (
	Energy        PostApiV1FilesUploadMultipartBodyDataType = "energy"
	Environmental PostApiV1FilesUploadMultipartBodyDataType = "environmental"
	Financial     PostApiV1FilesUploadMultipartBodyDataType = "financial"
	Personnel     PostApiV1FilesUploadMultipartBodyDataType = "personnel"
	Production    PostApiV1FilesUploadMultipartBodyDataType = "production"
)

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	// AccessToken JWT access токен
	AccessToken *string `json:"access_token,omitempty"`

	// ExpiresIn Время жизни access токена в секундах
	ExpiresIn *int `json:"expires_in,omitempty"`

	// RefreshToken JWT refresh токен
	RefreshToken *string           `json:"refresh_token,omitempty"`
	TokenType    *string           `json:"token_type,omitempty"`
	User         *UserInfoResponse `json:"user,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Details Дополнительные детали ошибки
	Details *map[string]interface{} `json:"details,omitempty"`

	// Error Код ошибки
	Error string `json:"error"`

	// Message Человеко-читаемое описание ошибки
	Message *string `json:"message,omitempty"`

	// RequestId Идентификатор запроса для трассировки
	RequestId *string    `json:"request_id,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// FileItem defines model for FileItem.
type FileItem struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// DataType Тип данных в файле
	DataType    *string             `json:"data_type,omitempty"`
	FileId      *openapi_types.UUID `json:"file_id,omitempty"`
	Filename    *string             `json:"filename,omitempty"`
	ProcessedAt *time.Time          `json:"processed_at,omitempty"`

	// Size Размер файла в байтах
	Size   *int            `json:"size,omitempty"`
	Status *FileItemStatus `json:"status,omitempty"`
}

// FileItemStatus defines model for FileItem.Status.
type FileItemStatus string

// FileListResponse defines model for FileListResponse.
type FileListResponse struct {
	Files      *[]FileItem `json:"files,omitempty"`
	Pagination *Pagination `json:"pagination,omitempty"`
}

// FileStatusResponse defines model for FileStatusResponse.
type FileStatusResponse struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// ErrorDetails Детали ошибки (если статус failed)
	ErrorDetails *string             `json:"error_details,omitempty"`
	FileId       *openapi_types.UUID `json:"file_id,omitempty"`
	Filename     *string             `json:"filename,omitempty"`

	// Message Детальное сообщение о статусе
	Message *string `json:"message,omitempty"`

	// ProcessedAt Время завершения обработки
	ProcessedAt *time.Time `json:"processed_at,omitempty"`

	// Progress Прогресс обработки в процентах
	Progress *int `json:"progress,omitempty"`

	// ResultUrl Ссылка на обработанные данные (если статус processed)
	ResultUrl *string                   `json:"result_url,omitempty"`
	Status    *FileStatusResponseStatus `json:"status,omitempty"`
	UpdatedAt *time.Time                `json:"updated_at,omitempty"`
}

// FileStatusResponseStatus defines model for FileStatusResponse.Status.
type FileStatusResponseStatus string

// FileUploadResponse defines model for FileUploadResponse.
type FileUploadResponse struct {
	// CreatedAt Время загрузки файла
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// EstimatedProcessingTime Примерное время обработки в секундах
	EstimatedProcessingTime *int `json:"estimated_processing_time,omitempty"`

	// FileId Уникальный идентификатор файла
	FileId *openapi_types.UUID `json:"file_id,omitempty"`

	// Filename Имя загруженного файла
	Filename *string `json:"filename,omitempty"`

	// Message Сообщение о статусе
	Message *string `json:"message,omitempty"`

	// Status Статус обработки файла
	Status *FileUploadResponseStatus `json:"status,omitempty"`
}

// FileUploadResponseStatus Статус обработки файла
type FileUploadResponseStatus string

// GenerateReportRequest defines model for GenerateReportRequest.
type GenerateReportRequest struct {
	// Filters Дополнительные фильтры для отчета
	Filters *map[string]interface{} `json:"filters,omitempty"`

	// Format Формат отчета
	Format *GenerateReportRequestFormat `json:"format,omitempty"`

	// ReportType Тип отчета
	ReportType GenerateReportRequestReportType `json:"report_type"`
	TimeRange  TimeRange                       `json:"time_range"`
}

// GenerateReportRequestFormat Формат отчета
type GenerateReportRequestFormat string

// GenerateReportRequestReportType Тип отчета
type GenerateReportRequestReportType string

// GenerateReportResponse defines model for GenerateReportResponse.
type GenerateReportResponse struct {
	// EstimatedCompletionTime Примерное время выполнения в секундах
	EstimatedCompletionTime *int `json:"estimated_completion_time,omitempty"`

	// Message Сообщение о статусе
	Message *string `json:"message,omitempty"`

	// ReportId Идентификатор задачи генерации отчета
	ReportId *openapi_types.UUID           `json:"report_id,omitempty"`
	Status   *GenerateReportResponseStatus `json:"status,omitempty"`
}

// GenerateReportResponseStatus defines model for GenerateReportResponse.Status.
type GenerateReportResponseStatus string

// HealthCheckResponse defines model for HealthCheckResponse.
type HealthCheckResponse struct {
	Components *struct {
		ApiGateway  *HealthCheckResponseComponentsApiGateway  `json:"api_gateway,omitempty"`
		AuthService *HealthCheckResponseComponentsAuthService `json:"auth_service,omitempty"`
		Clickhouse  *HealthCheckResponseComponentsClickhouse  `json:"clickhouse,omitempty"`
		Kafka       *HealthCheckResponseComponentsKafka       `json:"kafka,omitempty"`
		Postgres    *HealthCheckResponseComponentsPostgres    `json:"postgres,omitempty"`
		Redis       *HealthCheckResponseComponentsRedis       `json:"redis,omitempty"`
	} `json:"components,omitempty"`
	Status    *HealthCheckResponseStatus `json:"status,omitempty"`
	Timestamp *time.Time                 `json:"timestamp,omitempty"`

	// Version Версия API
	Version *string `json:"version,omitempty"`
}

// HealthCheckResponseComponentsApiGateway defines model for HealthCheckResponse.Components.ApiGateway.
type HealthCheckResponseComponentsApiGateway string

// HealthCheckResponseComponentsAuthService defines model for HealthCheckResponse.Components.AuthService.
type HealthCheckResponseComponentsAuthService string

// HealthCheckResponseComponentsClickhouse defines model for HealthCheckResponse.Components.Clickhouse.
type HealthCheckResponseComponentsClickhouse string

// HealthCheckResponseComponentsKafka defines model for HealthCheckResponse.Components.Kafka.
type HealthCheckResponseComponentsKafka string

// HealthCheckResponseComponentsPostgres defines model for HealthCheckResponse.Components.Postgres.
type HealthCheckResponseComponentsPostgres string

// HealthCheckResponseComponentsRedis defines model for HealthCheckResponse.Components.Redis.
type HealthCheckResponseComponentsRedis string

// HealthCheckResponseStatus defines model for HealthCheckResponse.Status.
type HealthCheckResponseStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	// Limit Количество элементов на странице
	Limit *int `json:"limit,omitempty"`

	// Page Текущая страница
	Page *int `json:"page,omitempty"`

	// Total Общее количество элементов
	Total *int `json:"total,omitempty"`

	// TotalPages Общее количество страниц
	TotalPages *int `json:"total_pages,omitempty"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	// RefreshToken Refresh токен для обновления access токена
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// CompanyName Название компании
	CompanyName string `json:"company_name"`

	// ContactPerson Контактное лицо
	ContactPerson *string `json:"contact_person,omitempty"`

	// Email Email пользователя
	Email openapi_types.Email `json:"email"`

	// Password Пароль пользователя (мин. 8 символов)
	Password string `json:"password"`

	// Phone Контактный телефон
	Phone *string `json:"phone,omitempty"`

	// Role Роль пользователя в системе
	Role RegisterRequestRole `json:"role"`
}

// RegisterRequestRole Роль пользователя в системе
type RegisterRequestRole string

// ReportItem defines model for ReportItem.
type ReportItem struct {
	// DownloadUrl Ссылка для скачивания отчета
	DownloadUrl *string `json:"download_url,omitempty"`

	// FileSize Размер файла отчета в байтах
	FileSize    *int                `json:"file_size,omitempty"`
	GeneratedAt *time.Time          `json:"generated_at,omitempty"`
	ReportId    *openapi_types.UUID `json:"report_id,omitempty"`
	ReportName  *string             `json:"report_name,omitempty"`
	ReportType  *string             `json:"report_type,omitempty"`
	TimeRange   *TimeRange          `json:"time_range,omitempty"`
}

// ReportListResponse defines model for ReportListResponse.
type ReportListResponse struct {
	Pagination *Pagination   `json:"pagination,omitempty"`
	Reports    *[]ReportItem `json:"reports,omitempty"`
}

// ReportResponse defines model for ReportResponse.
type ReportResponse struct {
	// Data Данные отчета
	Data        *map[string]interface{} `json:"data,omitempty"`
	DownloadUrl *string                 `json:"download_url,omitempty"`

	// ExpiresAt Время, после которого ссылка станет недействительной
	ExpiresAt   *time.Time          `json:"expires_at,omitempty"`
	GeneratedAt *time.Time          `json:"generated_at,omitempty"`
	ReportId    *openapi_types.UUID `json:"report_id,omitempty"`
	ReportName  *string             `json:"report_name,omitempty"`
	ReportType  *string             `json:"report_type,omitempty"`

	// Summary Сводка отчета
	Summary   *map[string]interface{} `json:"summary,omitempty"`
	TimeRange *TimeRange              `json:"time_range,omitempty"`
}

// SystemMetricsResponse defines model for SystemMetricsResponse.
type SystemMetricsResponse struct {
	// ActiveConnections Количество активных соединений
	ActiveConnections *int `json:"active_connections,omitempty"`

	// Goroutines Количество активных горутин
	Goroutines *int `json:"goroutines,omitempty"`

	// KafkaMessagesProcessed Количество обработанных сообщений Kafka
	KafkaMessagesProcessed *int `json:"kafka_messages_processed,omitempty"`

	// MemoryUsageMb Использование памяти в MB
	MemoryUsageMb *float32 `json:"memory_usage_mb,omitempty"`

	// RequestsPerSecond Запросов в секунду
	RequestsPerSecond *float32 `json:"requests_per_second,omitempty"`

	// UptimeSeconds Время работы системы в секундах
	UptimeSeconds *int `json:"uptime_seconds,omitempty"`
}

// TimeRange defines model for TimeRange.
type TimeRange struct {
	// EndDate Конечная дата периода
	EndDate openapi_types.Date `json:"end_date"`

	// StartDate Начальная дата периода
	StartDate openapi_types.Date `json:"start_date"`
}

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	// CompanyName Название компании
	CompanyName *string `json:"company_name,omitempty"`

	// ContactPerson Контактное лицо
	ContactPerson *string `json:"contact_person,omitempty"`

	// Phone Контактный телефон
	Phone *string `json:"phone,omitempty"`
}

// UserInfoResponse defines model for UserInfoResponse.
type UserInfoResponse struct {
	// CompanyName Название компании
	CompanyName *string `json:"company_name,omitempty"`

	// ContactPerson Контактное лицо
	ContactPerson *string `json:"contact_person,omitempty"`

	// CreatedAt Дата регистрации пользователя
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Email Email пользователя
	Email *openapi_types.Email `json:"email,omitempty"`

	// Id Уникальный идентификатор пользователя
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Phone Контактный телефон
	Phone *string `json:"phone,omitempty"`

	// Role Роль пользователя
	Role *UserInfoResponseRole `json:"role,omitempty"`

	// UpdatedAt Дата последнего обновления
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// UserInfoResponseRole Роль пользователя
type UserInfoResponseRole string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// GetApiV1AnalyticsReportsParams defines parameters for GetApiV1AnalyticsReports.
type GetApiV1AnalyticsReportsParams struct {
	Page       *int                                      `form:"page,omitempty" json:"page,omitempty"`
	Limit      *int                                      `form:"limit,omitempty" json:"limit,omitempty"`
	ReportType *GetApiV1AnalyticsReportsParamsReportType `form:"report_type,omitempty" json:"report_type,omitempty"`
}

// GetApiV1AnalyticsReportsParamsReportType defines parameters for GetApiV1AnalyticsReports.
type GetApiV1AnalyticsReportsParamsReportType string

// GetApiV1FilesParams defines parameters for GetApiV1Files.
type GetApiV1FilesParams struct {
	// Page Номер страницы
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit Количество элементов на странице
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Status Фильтр по статусу обработки
	Status *GetApiV1FilesParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetApiV1FilesParamsStatus defines parameters for GetApiV1Files.
type GetApiV1FilesParamsStatus string

// PostApiV1FilesUploadMultipartBody defines parameters for PostApiV1FilesUpload.
type PostApiV1FilesUploadMultipartBody struct {
	// DataType Тип загружаемых данных
	DataType *PostApiV1FilesUploadMultipartBodyDataType `json:"data_type,omitempty"`

	// Description Описание файла и типа данных
	Description *string `json:"description,omitempty"`

	// File Файл с промышленными данными
	File openapi_types.File `json:"file"`
}

// PostApiV1FilesUploadMultipartBodyDataType defines parameters for PostApiV1FilesUpload.
type PostApiV1FilesUploadMultipartBodyDataType string

// PostApiV1AnalyticsReportsGenerateJSONRequestBody defines body for PostApiV1AnalyticsReportsGenerate for application/json ContentType.
type PostApiV1AnalyticsReportsGenerateJSONRequestBody = GenerateReportRequest

// PostApiV1AuthLoginJSONRequestBody defines body for PostApiV1AuthLogin for application/json ContentType.
type PostApiV1AuthLoginJSONRequestBody = LoginRequest

// PostApiV1AuthRefreshJSONRequestBody defines body for PostApiV1AuthRefresh for application/json ContentType.
type PostApiV1AuthRefreshJSONRequestBody = RefreshRequest

// PostApiV1AuthRegisterJSONRequestBody defines body for PostApiV1AuthRegister for application/json ContentType.
type PostApiV1AuthRegisterJSONRequestBody = RegisterRequest

// PostApiV1FilesUploadMultipartRequestBody defines body for PostApiV1FilesUpload for multipart/form-data ContentType.
type PostApiV1FilesUploadMultipartRequestBody PostApiV1FilesUploadMultipartBody

// PutApiV1UsersProfileJSONRequestBody defines body for PutApiV1UsersProfile for application/json ContentType.
type PutApiV1UsersProfileJSONRequestBody = UpdateProfileRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Получение списка доступных отчетов
	// (GET /api/v1/analytics/reports)
	GetApiV1AnalyticsReports(w http.ResponseWriter, r *http.Request, params GetApiV1AnalyticsReportsParams)
	// Генерация нового отчета
	// (POST /api/v1/analytics/reports/generate)
	PostApiV1AnalyticsReportsGenerate(w http.ResponseWriter, r *http.Request)
	// Получение отчета
	// (GET /api/v1/analytics/reports/{report_id})
	GetApiV1AnalyticsReportsReportId(w http.ResponseWriter, r *http.Request, reportId openapi_types.UUID)
	// Аутентификация пользователя и получение токенов
	// (POST /api/v1/auth/login)
	PostApiV1AuthLogin(w http.ResponseWriter, r *http.Request)
	// Выход из системы
	// (POST /api/v1/auth/logout)
	PostApiV1AuthLogout(w http.ResponseWriter, r *http.Request)
	// Обновление access токена
	// (POST /api/v1/auth/refresh)
	PostApiV1AuthRefresh(w http.ResponseWriter, r *http.Request)
	// Регистрация нового пользователя (компании или администратора)
	// (POST /api/v1/auth/register)
	PostApiV1AuthRegister(w http.ResponseWriter, r *http.Request)
	// Получение списка загруженных файлов
	// (GET /api/v1/files)
	GetApiV1Files(w http.ResponseWriter, r *http.Request, params GetApiV1FilesParams)
	// Загрузка файла с промышленными данными
	// (POST /api/v1/files/upload)
	PostApiV1FilesUpload(w http.ResponseWriter, r *http.Request)
	// Удаление файла и связанных данных
	// (DELETE /api/v1/files/{file_id})
	DeleteApiV1FilesFileId(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID)
	// Получение статуса обработки файла
	// (GET /api/v1/files/{file_id})
	GetApiV1FilesFileId(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID)
	// Проверка состояния системы
	// (GET /api/v1/system/health)
	GetApiV1SystemHealth(w http.ResponseWriter, r *http.Request)
	// Получение метрик системы
	// (GET /api/v1/system/metrics)
	GetApiV1SystemMetrics(w http.ResponseWriter, r *http.Request)
	// Получение информации о текущем пользователе
	// (GET /api/v1/users/me)
	GetApiV1UsersMe(w http.ResponseWriter, r *http.Request)
	// Обновление профиля пользователя
	// (PUT /api/v1/users/profile)
	PutApiV1UsersProfile(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetApiV1AnalyticsReports operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1AnalyticsReports(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1AnalyticsReportsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "report_type" -------------

	err = runtime.BindQueryParameter("form", true, false, "report_type", r.URL.Query(), &params.ReportType)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "report_type", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1AnalyticsReports(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1AnalyticsReportsGenerate operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1AnalyticsReportsGenerate(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1AnalyticsReportsGenerate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1AnalyticsReportsReportId operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1AnalyticsReportsReportId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "report_id" -------------
	var reportId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", r.PathValue("report_id"), &reportId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "report_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1AnalyticsReportsReportId(w, r, reportId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1AuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1AuthLogin(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1AuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1AuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1AuthLogout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1AuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1AuthRefresh operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1AuthRefresh(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1AuthRefresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1AuthRegister operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1AuthRegister(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1AuthRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1Files operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1Files(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1FilesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1Files(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1FilesUpload operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1FilesUpload(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1FilesUpload(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiV1FilesFileId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiV1FilesFileId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "file_id" -------------
	var fileId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "file_id", r.PathValue("file_id"), &fileId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "file_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiV1FilesFileId(w, r, fileId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1FilesFileId operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1FilesFileId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "file_id" -------------
	var fileId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "file_id", r.PathValue("file_id"), &fileId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "file_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1FilesFileId(w, r, fileId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1SystemHealth operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1SystemHealth(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1SystemHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1SystemMetrics operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1SystemMetrics(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1SystemMetrics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1UsersMe operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1UsersMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1UsersMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutApiV1UsersProfile operation middleware
func (siw *ServerInterfaceWrapper) PutApiV1UsersProfile(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutApiV1UsersProfile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/v1/analytics/reports", wrapper.GetApiV1AnalyticsReports)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/analytics/reports/generate", wrapper.PostApiV1AnalyticsReportsGenerate)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/analytics/reports/{report_id}", wrapper.GetApiV1AnalyticsReportsReportId)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/auth/login", wrapper.PostApiV1AuthLogin)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/auth/logout", wrapper.PostApiV1AuthLogout)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/auth/refresh", wrapper.PostApiV1AuthRefresh)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/auth/register", wrapper.PostApiV1AuthRegister)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/files", wrapper.GetApiV1Files)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/files/upload", wrapper.PostApiV1FilesUpload)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/v1/files/{file_id}", wrapper.DeleteApiV1FilesFileId)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/files/{file_id}", wrapper.GetApiV1FilesFileId)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/system/health", wrapper.GetApiV1SystemHealth)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/system/metrics", wrapper.GetApiV1SystemMetrics)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/users/me", wrapper.GetApiV1UsersMe)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1/users/profile", wrapper.PutApiV1UsersProfile)

	return m
}
